@startuml
'https://plantuml.com/sequence-diagram

actor Client as c
participant Products as p
participant Service as s
participant Vehicle as v
participant License as l
participant LicenseController as lc
database Database as db

c->p: views products
c->p: buys product
p->s: getServices()
p->p: selectRuntime()
p->lc: buyProduct()
lc->db: saveLicense()
c->v: startsCar()
v->db:saveVin()
lc->db:getLicense()



@enduml