@startuml
'https://plantuml.com/sequence-diagram

actor Client as c
participant PurchaseSystem as ps
participant BuyController as co
participant BuyService as s
'participant LicenseController as lc
participant LicenseService as ls
participant License as l
participant CarRepository as ca
participant ProductsRepository as p
participant LicenseRepository as lr
database Database as db

c->ps : doPurchase()
activate ps
ps->c : returnCompleted(): boolean
deactivate ps
c -> co: getMapping(): CustomerID, ProductID, Duration, Vin

co-> s: buy(CustomerID, ProductID, Duration, Vin): void
activate s
's -> ca: setProduct(ProductId, Vin)
'ca -> ls: setService(ServiceID)

s-> ls: createLicenses(Duration, ProductID)
activate ls
ls->p: getServices(ProductID)
p-->ls: returnServices(List<Services>)

ls->  l: createLicense(List<Services>, Duration)

l-->ls: returnLicense(List<License>)



ls-> lr: writeLicense(List<Services>, Duration)
lr->db: update Licenses
db-->lr: return List<License>
lr-->  ls: return Updated Licenses: List<Services>
ls->s: returnLicense(List<License>)
deactivate ls

deactivate s




@enduml