@startuml
'https://plantuml.com/sequence-diagram

actor Client as c
participant BuyController as co
participant Car as ca
participant Products as p
participant BuyService as s
participant LicenseController as lc
participant License as l
database Database as db

c -> co:
co-> s:CustomerID, ProductId, Duration
s->  l: BuyMethod()





@enduml