@startuml
left to right direction

actor "Customer" as at
rectangle System{



(Buy Product) ---> (Select compatible Product with Services): <<include>>
(Select compatible Product with Services) ----> (Select Runtime 3/6/9/12): <<include>>
(Select Runtime 3/6/9/12) ->(Purchase)



(View Compatible Products)---> (View runtime 3/6/9/12): << include>>


(View active Licenses)->(View Vehicle License List)
}

at --> (View Compatible Products)
at --> (Buy Product)
at -> (View active Licenses)

@enduml