@startuml
class PurchaseRequest{
productsDurations: List<Pair<ArticleNumber,Duration>
vin: Vin
customerId: CustomerId
}
@enduml
@startuml

actor Customer

Customer -> OrderRESTController : buy(purchaseRequest)
activate OrderRESTController


OrderRESTController -> OrderService : buy(purchaseRequest)
activate OrderService



OrderService --> OrderStore : createAndPersistOrder(purchaseRequest))
activate OrderStore
OrderStore --> OrderService : order
deactivate OrderStore


OrderService -> ExternalPaymentServiceRestController : processPayment(order.id, order.customer.paymentInfo, order.totalPrice)
activate ExternalPaymentServiceRestController

ExternalPaymentServiceRestController --> OrderService : paymentStatus
deactivate ExternalPaymentServiceRestController

OrderService --> OrderRESTController : orderId
deactivate OrderService

OrderRESTController --> Customer : orderId
deactivate OrderRESTController

@enduml
