@startuml

class Service{
id:long
name:String
rightToUseFrom: Date
rightToUseTo:Date
}

@enduml

@startuml

actor Customer

Customer -> ActiveServiceRESTController : getActiveServices(vin, customerId)
activate ActiveServiceRESTController

ActiveServiceRESTController -> ActiveServiceService : getActiveServices(vin, customerId)
activate ActiveServiceService

ActiveServiceService -> VehicleStore : getActiveServices(vin,customerId)
activate VehicleStore

VehicleStore -> VehicleRepository: getUsageRights(vin, customerId)
activate VehicleRepository
VehicleRepository --> VehicleStore : usageRights

VehicleStore -> VehicleStore: convertToServices(usageRights)
activate VehicleStore
VehicleStore --> VehicleStore: List<Service>
deactivate VehicleStore
VehicleStore --> ActiveServiceService : List<Service>
deactivate VehicleStore



ActiveServiceService --> ActiveServiceRESTController : List<Service>
deactivate ActiveServiceService

ActiveServiceRESTController --> Customer : List<Service>
deactivate ActiveServiceRESTController

@enduml