@startuml

class Product {
    - productId: long
    - name: string
    - serviceList: List<Service>
    - duration: int
    + getServiceList(): List<Service>

}

class Service {
    - serviceId: long
    - name: string

}


class License {
    - licenseId: long
    - start: date
    - end: date
    - product: Product
    - service: Service
    - vin: String
    - Order: Order
}

class LicenseRepository{

    +getLicensesFromDb(vin): List<License>
    +writeLicenses(List<License>, vin): boolean
    +deleteLicenseWithOrderId(orderId): boolean

}

class ViewLicenseController {
    + getLicense(String vin): List<License>
}

class ViewOrderController{
    +getOrder(String orderID):Order
}
ViewOrderController--OrderService
class BuyController {

    + doPurchase(vin, customerId, productId): boolean
    + purchaseConfirmed(OrderId): boolean
    + writeOrder(Order)
}
class CancellationController{
+ cancelOrder(orderId): boolean
}
CancellationController -- LicenseService
LicenseService--OrderService


class OrderRepository{
+writeOrder(Order)
+getOrder(orderId):Order
+updateOrder(Order):boolean
}

class Order{
-OrderId: String
-vin: String
-date: Date
-Products: List<Product>
- isCancelled: Boolean
- CancellationDate: Date
}

class OrderService{
    -Order
    +writeOrder(Order)
    +getOrder(orderId):Order
    +buyConfirmed(Order)
    +updateOrder(Order):boolean
}

class LicenseService{

    + createLicense(ProductId, vin)
    + getLicense(String vin)): List<License>

}

class BuyService {

    +createLicenses(List<Product>, vin)
}

LicenseRepository-- License
LicenseRepository -- LicenseService
BuyService -- LicenseService
ViewLicenseController -- LicenseService
BuyController --> OrderService

BuyService -- BuyController
License "0.*" --"1"  Order

License "0.*" --> "1"Product
Product "0..*" --> "0..*" Service
OrderService --> OrderRepository
Order --> OrderService
@enduml



