@startuml
class Car {
    - vin: string
    '- owner: Customer
    '- serviceList: List<Service>
    '- licenseList: List<License>

    '+ setLicenseList(List<License> licenseList): void
    '+ setserviceList(List<Service> serviceList): void
    '+ setOwner(Customer c): void
    '+ getServiceList(): List<Service>
    + getVin(): String

}

'class CarRepository{

  '  + getCarFromDb((String vin): Car


'}

class Customer {
    - customerId: long
    - name: string
    - car: List<Car>

    + addCar(String vin): void


}

'class CustomerRepository{}

'class ProductRepository{}


class Product {
    - productId: long
    - name: string
    - serviceList: List<Service>
    '- price: double
    - duration: int

    '+ setPrice(double price): void
    + getServiceList(): List<Service>

}



class Service {
    - serviceId: long
    - name: string
    - description: string
    - duration: int
    - productList: List<Product>

    + setDuration(int duration): void
    + getProductList(): List<Product>


}

'class ServiceRepository{

 '   +getServiceFromDb(serviceId): Service

'}

class License {
    - licenseId: long
    - start: date
    - end: date
    - product: Product
    - service: Service
    - vin: String

   '+ extendLicense(license: License, duration: int): void

}

class LicenseRepository{

    +getLicensesFromDb(vin): List<License>
    +writeLicenses(List<License>, vin): boolean

}

class ViewLicenseController {


    + getLicense(String vin): List<License>

}

class BuyController {

    + doPurchase(vin, customerId, productId): boolean
    + purchaseConfirmed(OrderId): boolean
    'Kaufdatum?
}

class OrderRepository{
+writeOrder(Order)
+getOrder(id)
}

class Order{
-OrderId: int
-vin:String
-date: String
-Products: List<Product>

}


'class ViewProductController {

 '   + getProductList(String vin): List<Product>

'}

class LicenseService{

    + createLicense(ProductId, vin)
    + getLicense(String vin)): List<License>

}

class BuyService {

    +createLicenses(List<Product>, vin)
}

'class ViewProductService {

 '   + getCar(String vin): Car
  '  + addProductsToNewProductList(List<Product>):List<Product>
'}







LicenseRepository-- License
LicenseRepository -- LicenseService
BuyService -- LicenseService
ViewLicenseController -- LicenseService
BuyController -- OrderRepository
Order -- OrderRepository
'CarRepository -- Lice  nseService
'ProductRepository -- Product
'CarRepository -- ViewProductService

'ViewProductController -- ViewProductService
BuyService -- BuyController
'CarRepository -- Car
'CustomerRepository -- Customer
'ServiceRepository -- Service
Customer "1" --> "0..*" Car
Car "1" --> "0..*" License
'Car "1" --> "0..*" Service
License "0..*"--> "1"Product
Product "0..*" --> "0..*" Service

@enduml



