@startuml
'https://plantuml.com/sequence-diagram
autonumber
actor Customer as c

participant BuyController as co
participant PurchaseSystem as ps
participant BuyService as s

participant LicenseService as ls



participant LicenseRepository as lr
database Database as db

c-> co : doPurchase(List<Product>, sum, vin)
co -> ps: doPurchase(OrderId, sum)
activate ps
ps->co : purchaseConfirmed(OrderId): boolean
deactivate ps
co-> s: buyConfirmed(List<Product>, vin)
activate s
loop for(Product p : List<Product>)
    s-> ls: createLicenses(ProductID)
    activate ls
    loop for(Service s : List<Service>)
        ls -> ls : new License()
        end
        ls -> lr: writeLicense(List<License>, vin)
        lr -> db:writeLicense(List<License>, vin)
        db -> lr: return boolean
        lr --> ls: return boolean
        ls-->s: return boolean
        deactivate ls
    end
s --> co: return boolean
co --> c: return boolean




@enduml