@startuml
'https://plantuml.com/sequence-diagram

autonumber

Actor Customer as c
Participant ViewLicenseControler as vlc
Participant LicenseService as ls
Participant LicenseRepository as cr
database Database as db

c --->vlc:View Services (String VIN)
activate vlc
vlc -> ls:getLicenses(String VIN): List<Licenses>
activate ls
ls -> cr: getLicenses(String VIN): List<Licenses>
activate cr
cr->db: getLicensesFromDb(vin): List<Licenses>
activate db
db-->cr: Return List<Licenses> from Query
deactivate db
cr-->ls: return List<Licenses>
deactivate cr
loop for(License l : LicenseList())
    ls->ls: addServiceToServiceList()
    end

ls-->vlc: return List<Services>
deactivate ls
vlc-->c: View Services List<Services>
deactivate vlc

@enduml