@startuml
left to right direction

actor "Customer" as at
rectangle System{



(Buy Product)  -->(Purchase)


'auskommentiert, weil aktuell nicht benötigt
'(View Compatible Products)---> (View runtime 3/6/9/12): << include>>


(View active Licenses)-->(View Vehicle License List)
(Cancel product)-->(Delete usage rights)
(Delete usage rights)-->(Safe cancellation)
(View products with OrderId)-->(View details)
}

'at --> (View Compatible Products)
at --> (Buy Product)
at -> (View active Licenses)
at -->(Cancel product)
at -->(View products with OrderId)
@enduml