@startuml
left to right direction

actor "Customer" as at
rectangle System{



(Buy Product)  ->(Purchase)


'auskommentiert, weil aktuell nicht benötigt
'(View Compatible Products)---> (View runtime 3/6/9/12): << include>>


(View active Licenses)-->(View Vehicle License List)
}

'at --> (View Compatible Products)
at --> (Buy Product)
at -> (View active Licenses)

@enduml